import { ChevronDown, Globe2, Play, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Textarea } from "@/components/ui/textarea";
import { Nation, ScenarioConfig } from "@/lib/sandtable";

type Props = { visible:boolean; config:ScenarioConfig; setConfig:(config:ScenarioConfig)=>void; nations:Nation[]; running:boolean; onRun:()=>void; onClose:()=>void };

export function AgentSetupPanel({visible,config,setConfig,nations,running,onRun,onClose}:Props) {
  const patch = <K extends keyof ScenarioConfig>(key:K,value:ScenarioConfig[K]) => setConfig({...config,[key]:value});
  const patchSide = (side:"sideA"|"sideB",nationCode:string) => setConfig({...config,[side]:{...config[side],nationCode}});
  const selectedA=nations.find(nation=>nation.code===config.sideA.nationCode);
  const selectedB=nations.find(nation=>nation.code===config.sideB.nationCode);
  const asOf=[selectedA?.as_of_date,selectedB?.as_of_date].filter(Boolean).sort().at(-1);
  return <aside className={`absolute bottom-0 left-0 top-[76px] z-40 flex w-full flex-col border-r border-white/10 bg-[#080808]/98 shadow-[24px_0_70px_rgba(0,0,0,.36)] backdrop-blur-xl transition-transform duration-300 sm:w-[420px] ${visible?"translate-x-0":"-translate-x-full"}`} aria-label="Configure national agent simulation">
    <div className="flex items-center justify-between border-b border-white/8 px-5 py-5"><div><p className="text-[9px] uppercase tracking-[.18em] text-yellow-300">Future conflict exercise</p><h2 className="mt-1 text-xl font-semibold tracking-tight">Configure agents</h2></div><Button onClick={onClose} size="icon" variant="ghost" className="h-10 w-10 rounded-xl text-stone-500" aria-label="Close configuration"><Globe2 className="h-4 w-4"/></Button></div>
    <div className="flex-1 overflow-y-auto px-5 py-6">
      <p className="text-sm leading-relaxed text-stone-500">Choose two national profiles and one strategic question. AI agents will adapt aggregate stance, readiness, logistics, resilience, and diplomacy each week.</p>
      <div className="mt-7 grid grid-cols-2 gap-3"><NationField label="Side A" value={config.sideA.nationCode} nations={nations.filter(n=>n.code!==config.sideB.nationCode)} onChange={value=>patchSide("sideA",value)}/><NationField label="Side B" value={config.sideB.nationCode} nations={nations.filter(n=>n.code!==config.sideA.nationCode)} onChange={value=>patchSide("sideB",value)}/></div>
      <label className="mt-6 block"><span className="mb-2 block text-[10px] uppercase tracking-[.14em] text-stone-600">Strategic scenario</span><Textarea value={config.objective} onChange={event=>patch("objective",event.target.value)} placeholder="Describe a bounded future strategic objective…" className="min-h-28 resize-none rounded-2xl border-white/10 bg-black/35 p-4 text-sm leading-relaxed text-stone-200 placeholder:text-stone-700"/></label>
      <div className="mt-7 space-y-6"><Range label="Duration" value={config.duration} min={4} max={24} suffix=" weeks" onChange={value=>patch("duration",value)}/><Range label="Uncertainty" value={config.uncertainty} min={10} max={90} suffix="%" onChange={value=>patch("uncertainty",value)}/></div>
      <details className="group mt-7 rounded-2xl border border-white/8 bg-black/25"><summary className="flex h-12 cursor-pointer list-none items-center justify-between px-4 text-[10px] uppercase tracking-[.14em] text-stone-500">Model assumptions<ChevronDown className="h-3.5 w-3.5 transition-transform group-open:rotate-180"/></summary><div className="grid grid-cols-2 gap-3 border-t border-white/8 p-4"><Choice label="Terrain" value={config.terrain} options={["open","mixed","restricted","maritime"]} onChange={value=>patch("terrain",value as ScenarioConfig["terrain"])}/><Choice label="Tempo" value={config.tempo} options={["measured","standard","intense"]} onChange={value=>patch("tempo",value as ScenarioConfig["tempo"])}/></div></details>
      <div className="mt-6 flex gap-3 rounded-2xl border border-yellow-400/15 bg-yellow-400/[.04] p-4"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-yellow-300"/><p className="text-[10px] leading-relaxed text-stone-500">Versioned public macro data{asOf?` · as of ${new Date(asOf).toLocaleDateString()}`:""}. No live intelligence, target selection, weapon guidance, attack routes, or real-unit locations.</p></div>
    </div>
    <div className="border-t border-white/8 bg-[#090909] p-4"><Button onClick={onRun} disabled={running||!config.objective.trim()} className="stable-action h-13 w-full rounded-2xl bg-yellow-400 text-sm font-semibold text-[#181500] hover:bg-yellow-300"><Play className="mr-2 h-4 w-4 fill-current"/>{running?"Starting national agents…":"Run agent simulation"}</Button></div>
  </aside>;
}

function NationField({label,value,nations,onChange}:{label:string;value:string;nations:Nation[];onChange:(value:string)=>void}) { return <label><span className="mb-2 block text-[10px] uppercase tracking-[.14em] text-stone-600">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="h-12 rounded-xl border-white/10 bg-black/35 text-xs text-stone-200"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111] text-stone-200">{nations.map(nation=><SelectItem key={nation.code} value={nation.code}>{nation.code} · {nation.name}</SelectItem>)}</SelectContent></Select></label> }
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}) { return <label><span className="mb-2 block text-[9px] text-stone-600">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="h-11 rounded-xl border-white/10 bg-black/35 text-xs capitalize"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111] text-stone-200">{options.map(option=><SelectItem key={option} value={option} className="capitalize">{option}</SelectItem>)}</SelectContent></Select></label> }
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void}) { return <div><div className="mb-2.5 flex justify-between text-[10px]"><span className="uppercase tracking-[.14em] text-stone-600">{label}</span><span className="font-mono text-stone-300">{value}{suffix}</span></div><Slider value={[value]} min={min} max={max} onValueChange={values=>onChange(values[0])}/></div> }
