import { FormEvent, useMemo, useState } from "react";
import { Archive, Bot, ChevronDown, Globe2, Play, Save, Send, Share2, SlidersHorizontal, Sparkles, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Nation, ScenarioConfig, SimulationResult } from "@/lib/sandtable";

export type ConversationProposal = { title:string; summary:string; objective:string; terrain:ScenarioConfig["terrain"]; tempo:ScenarioConfig["tempo"]; duration:number; uncertainty:number; formations?:{sideA:ScenarioConfig["sideA"]["formations"];sideB:ScenarioConfig["sideB"]["formations"]}; assumptions:string[]; alternatives:string[]; safetyNotice:string };
type Props = { visible:boolean; config:ScenarioConfig; setConfig:(config:ScenarioConfig)=>void; nations:Nation[]; result?:SimulationResult; week:number; running:boolean; saving:boolean; proposal?:ConversationProposal; proposalLoading:boolean; onRequestProposal:(prompt:string)=>void; onApplyProposal:()=>void; onDiscardProposal:()=>void; onRun:()=>void; onSave:()=>void; onShare:()=>void; onOpenStudies:()=>void; onShowGlobe:()=>void };

export function ConversationPanel(props:Props) {
  const { visible,config,setConfig,nations,result,week,running,saving,proposal,proposalLoading,onRequestProposal,onApplyProposal,onDiscardProposal,onRun,onSave,onShare,onOpenStudies,onShowGlobe } = props;
  const [prompt,setPrompt] = useState("");
  const patch = <K extends keyof ScenarioConfig>(key:K,value:ScenarioConfig[K]) => setConfig({...config,[key]:value});
  const patchSide = (side:"sideA"|"sideB", key:string, value:unknown) => setConfig({...config,[side]:{...config[side],[key]:value}});
  const activeFrame = result?.frames[Math.min(week,result.frames.length-1)];
  const visibleEvents = useMemo(()=>result?.events.filter(event=>event.week<=week).slice(-3).reverse() ?? [],[result,week]);
  const turningWeek = useMemo(()=>result ? result.frames.slice(1).reduce((best,frame,index)=>{const previous=result.frames[index];const change=Math.abs(frame.aStrength-previous.aStrength)+Math.abs(frame.bStrength-previous.bStrength);return change>best.change?{week:frame.week,change}:best;},{week:0,change:0}).week : 0,[result]);
  const submit = (event:FormEvent) => { event.preventDefault(); const value=prompt.trim(); if(!value)return; onRequestProposal(value); setPrompt(""); };

  return <aside className={`absolute left-0 top-[72px] z-40 flex w-full flex-col border-r border-white/10 bg-[#080808]/98 shadow-[24px_0_70px_rgba(0,0,0,.32)] backdrop-blur-xl transition-[transform,bottom] duration-300 md:bottom-0 md:w-[430px] md:translate-x-0 lg:w-[460px] ${result?"bottom-[84px]":"bottom-0"} ${visible?"translate-x-0":"-translate-x-full"}`} aria-label="Sandtable conversation">
    <div className="flex h-14 shrink-0 items-center justify-between border-b border-white/8 px-4">
      <div><p className="text-xs font-semibold text-stone-200">Scenario conversation</p><p className="mt-0.5 text-[9px] uppercase tracking-[.16em] text-stone-600">Review · configure · resolve</p></div>
      <div className="flex items-center gap-1"><Button onClick={onOpenStudies} variant="ghost" size="icon" className="h-10 w-10 rounded-xl text-stone-500" aria-label="Open saved studies"><Archive className="h-4 w-4"/></Button><Button onClick={onShowGlobe} variant="ghost" className="h-10 rounded-xl px-3 text-xs text-yellow-300 md:hidden"><Globe2 className="mr-2 h-4 w-4"/>Globe</Button></div>
    </div>

    <div className="conversation-scroll flex-1 space-y-5 overflow-y-auto px-3 py-5 sm:px-4">
      <Message role="assistant"><p className="text-sm leading-relaxed text-stone-300">Describe an abstract study or configure the scenario cards below. I’ll keep every assumption visible before the deterministic model runs.</p><div className="mt-3 flex flex-wrap gap-1.5">{["Aggregate only","Seeded replay","Not a forecast"].map(tag=><span key={tag} className="rounded-full border border-white/8 bg-white/[.03] px-2.5 py-1 text-[9px] text-stone-500">{tag}</span>)}</div></Message>

      <Message role="user" label="Scenario configuration">
        <div className="space-y-3"><Field label="Study name"><Input value={config.name} onChange={event=>patch("name",event.target.value)} className="conversation-control"/></Field><Field label="Abstract objective"><Textarea value={config.objective} onChange={event=>patch("objective",event.target.value)} className="min-h-16 rounded-xl border-white/10 bg-black/30 text-xs"/></Field><div className="grid grid-cols-2 gap-2"><NationSelect label="Side A" value={config.sideA.nationCode} nations={nations.filter(n=>n.code!==config.sideB.nationCode)} onChange={value=>patchSide("sideA","nationCode",value)}/><NationSelect label="Side B" value={config.sideB.nationCode} nations={nations.filter(n=>n.code!==config.sideA.nationCode)} onChange={value=>patchSide("sideB","nationCode",value)}/></div></div>
      </Message>

      <Message role="assistant" label="Environment card">
        <div className="grid grid-cols-2 gap-2"><Choice label="Terrain" value={config.terrain} options={["open","mixed","restricted","maritime"]} onChange={value=>patch("terrain",value as ScenarioConfig["terrain"])}/><Choice label="Tempo" value={config.tempo} options={["measured","standard","intense"]} onChange={value=>patch("tempo",value as ScenarioConfig["tempo"])}/></div><div className="mt-4 space-y-4"><Range label="Duration" value={config.duration} min={4} max={24} suffix=" weeks" onChange={value=>patch("duration",value)}/><Range label="Uncertainty" value={config.uncertainty} min={10} max={90} suffix="%" onChange={value=>patch("uncertainty",value)}/></div>
      </Message>

      <Message role="assistant" label="Force posture card">
        <Tabs defaultValue="sideA"><TabsList className="grid h-10 w-full grid-cols-2 rounded-xl bg-black/40 p-1"><TabsTrigger value="sideA" className="rounded-lg text-xs data-[state=active]:bg-yellow-400 data-[state=active]:text-black">Side A</TabsTrigger><TabsTrigger value="sideB" className="rounded-lg text-xs data-[state=active]:bg-stone-200 data-[state=active]:text-black">Side B</TabsTrigger></TabsList>{(["sideA","sideB"] as const).map((side,index)=><TabsContent key={side} value={side} className="mt-4 space-y-4"><Choice label="Posture" value={config[side].posture} options={["defensive","balanced","assertive"]} onChange={value=>patchSide(side,"posture",value)}/><Range label="Allocation" value={config[side].allocation} min={20} max={100} suffix="%" onChange={value=>patchSide(side,"allocation",value)}/><Range label="Supply" value={config[side].supply} min={20} max={100} suffix="%" onChange={value=>patchSide(side,"supply",value)}/><details className="group rounded-xl border border-white/8 bg-black/25"><summary className="flex h-11 cursor-pointer list-none items-center justify-between px-3 text-[10px] uppercase tracking-[.14em] text-stone-500">Advanced posture<ChevronDown className="h-3.5 w-3.5 transition-transform group-open:rotate-180"/></summary><div className="space-y-4 border-t border-white/8 p-3"><Range label="Support" value={config[side].support} min={10} max={100} suffix="%" onChange={value=>patchSide(side,"support",value)}/><Range label="Reinforcement" value={config[side].reinforcements} min={0} max={60} suffix="%" onChange={value=>patchSide(side,"reinforcements",value)}/><FormationInputs side={index===0?"A":"B"} formations={config[side].formations} onChange={(kind,value)=>patchSide(side,"formations",{...config[side].formations,[kind]:value})}/></div></details></TabsContent>)}</Tabs>
      </Message>

      <Message role="user" label="Run request"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-mono text-[10px] text-stone-400">Seed · {config.seed}</p><p className="mt-1 text-[10px] text-stone-600">{config.duration} weekly ticks · 240 samples</p></div><Button onClick={onRun} disabled={running} className="h-11 shrink-0 rounded-xl bg-yellow-400 px-4 text-xs font-semibold text-[#181500] hover:bg-yellow-300"><Play className="mr-2 h-3.5 w-3.5 fill-current"/>{running?"Resolving…":"Run model"}</Button></div></Message>

      {proposalLoading&&<Message role="assistant" label="Drafting proposal"><Typing/></Message>}
      {proposal&&<Message role="assistant" label="Reviewable AI proposal"><p className="text-sm font-medium text-stone-100">{proposal.title}</p><p className="mt-2 text-xs leading-relaxed text-stone-400">{proposal.summary}</p><div className="mt-3 grid grid-cols-2 gap-2"><Mini label="Terrain" value={proposal.terrain}/><Mini label="Tempo" value={proposal.tempo}/><Mini label="Duration" value={`${proposal.duration} weeks`}/><Mini label="Uncertainty" value={`${proposal.uncertainty}%`}/></div><p className="mt-3 text-[10px] leading-relaxed text-yellow-100">{proposal.safetyNotice}</p><div className="mt-4 flex justify-end gap-2"><Button onClick={onDiscardProposal} variant="ghost" className="h-10 rounded-xl text-xs">Discard</Button><Button onClick={onApplyProposal} className="h-10 rounded-xl bg-yellow-400 text-xs text-black hover:bg-yellow-300">Apply to cards</Button></div></Message>}
      {running&&<Message role="assistant" label="Simulation in progress"><div className="space-y-2"><ProgressLine label="Resolving canonical replay"/><ProgressLine label="Running deterministic sample seeds" delay/><ProgressLine label="Assembling ranges and event log" delay/></div></Message>}
      {result&&<><Message role="assistant" label="Simulation complete"><div className="grid grid-cols-2 gap-2"><ResultMetric label="Modeled advantage" value={`Side ${result.advantage}`} accent/><ResultMetric label="Confidence" value={result.confidence}/><ResultMetric label="Side A ensemble" value={`${result.outcomeA}%`}/><ResultMetric label="Side B ensemble" value={`${result.outcomeB}%`}/></div><p className="mt-3 rounded-xl border border-yellow-400/15 bg-yellow-400/[.05] p-3 text-[10px] leading-relaxed text-stone-400">Illustrative model output—not a forecast or operational recommendation.</p><div className="mt-3 grid grid-cols-2 gap-2"><Button onClick={onSave} disabled={saving} variant="outline" className="h-10 rounded-xl border-white/10 bg-transparent text-xs"><Save className="mr-2 h-3.5 w-3.5"/>{saving?"Saving…":"Save"}</Button><Button onClick={onShare} className="h-10 rounded-xl bg-yellow-400 text-xs text-black hover:bg-yellow-300"><Share2 className="mr-2 h-3.5 w-3.5"/>Share</Button></div></Message>
      <Message role="assistant" label={`Replay · week ${week}`}><div className="flex items-center justify-between"><p className="text-xs text-stone-400">{activeFrame?.control==="contested"?"The objective remains contested.":`Side ${activeFrame?.control} holds the modeled objective state.`}</p><span className="rounded-full bg-yellow-400/10 px-2 py-1 font-mono text-[9px] text-yellow-200">W{String(week).padStart(2,"0")}</span></div>{visibleEvents.length>0&&<div className="mt-3 space-y-2">{visibleEvents.map(event=><div key={event.id} className="rounded-xl border border-white/8 bg-black/30 p-3"><p className="text-[9px] uppercase tracking-wider text-stone-600">{event.type} · side {event.side}</p><p className="mt-1 text-xs text-stone-300">{event.title}</p></div>)}</div>}</Message>
      <Message role="assistant" label="Interpretation"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-yellow-400/10 text-yellow-300"><Sparkles className="h-4 w-4"/></span><div><p className="text-sm text-stone-200">Modeled turning point: week {turningWeek}</p><p className="mt-1 text-xs leading-relaxed text-stone-500">{config.tempo} tempo and the final supply balance were the strongest visible drivers in the preserved replay. This interpretation adds no external intelligence.</p></div></div></Message></>}
      <div className="h-2"/>
    </div>

    <form onSubmit={submit} className="shrink-0 border-t border-white/8 bg-[#090909] p-3"><div className="relative"><Textarea value={prompt} onChange={event=>setPrompt(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();event.currentTarget.form?.requestSubmit();}}} placeholder="Describe an abstract scenario…" className="min-h-[52px] resize-none rounded-2xl border-white/10 bg-white/[.035] py-3 pl-4 pr-14 text-sm placeholder:text-stone-600" aria-label="Scenario prompt"/><Button type="submit" disabled={!prompt.trim()||proposalLoading} size="icon" className="absolute bottom-2 right-2 h-9 w-9 rounded-xl bg-yellow-400 text-black hover:bg-yellow-300" aria-label="Send scenario prompt"><Send className="h-4 w-4"/></Button></div><div className="mt-2 flex items-center justify-between px-1 text-[9px] text-stone-600"><span>AI drafts require explicit review</span><span>Shift + Enter for line break</span></div></form>
  </aside>;
}

function Message({role,label,children}:{role:"assistant"|"user";label?:string;children:React.ReactNode}) { const Icon=role==="assistant"?Bot:UserRound; return <article className={`flex gap-2.5 ${role==="user"?"flex-row-reverse":""}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-xl border ${role==="assistant"?"border-yellow-400/25 bg-yellow-400/10 text-yellow-300":"border-white/10 bg-white/[.05] text-stone-300"}`}><Icon className="h-3.5 w-3.5"/></span><div className={`min-w-0 flex-1 rounded-2xl border p-4 ${role==="assistant"?"rounded-tl-md border-white/8 bg-white/[.025]":"rounded-tr-md border-yellow-400/15 bg-yellow-400/[.045]"}`}>{label&&<p className="mb-3 text-[9px] uppercase tracking-[.17em] text-stone-600">{label}</p>}{children}</div></article> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="block"><span className="mb-1.5 block text-[10px] text-stone-500">{label}</span>{children}</label> }
function NationSelect({label,value,nations,onChange}:{label:string;value:string;nations:Nation[];onChange:(value:string)=>void}) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger className="conversation-control"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111] text-stone-200">{nations.map(nation=><SelectItem key={nation.code} value={nation.code}>{nation.code} · {nation.name}</SelectItem>)}</SelectContent></Select></Field> }
function Choice({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger className="conversation-control capitalize"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111] text-stone-200">{options.map(option=><SelectItem key={option} value={option} className="capitalize">{option}</SelectItem>)}</SelectContent></Select></Field> }
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void}) { return <div><div className="mb-2 flex justify-between text-[10px]"><span className="text-stone-500">{label}</span><span className="font-mono text-stone-300">{value}{suffix}</span></div><Slider value={[value]} min={min} max={max} onValueChange={values=>onChange(values[0])} className="py-2"/></div> }
function FormationInputs({side,formations,onChange}:{side:"A"|"B";formations:ScenarioConfig["sideA"]["formations"];onChange:(kind:keyof ScenarioConfig["sideA"]["formations"],value:number)=>void}) { return <div><p className="mb-2 text-[10px] text-stone-500">Aggregate formations · Side {side}</p><div className="grid grid-cols-4 gap-1.5">{(["land","air","naval","support"] as const).map(kind=><label key={kind} className="rounded-lg border border-white/8 bg-black/30 p-2 text-center"><span className="block text-[8px] capitalize text-stone-600">{kind}</span><Input type="number" min={0} max={12} value={formations[kind]} onChange={event=>onChange(kind,Math.max(0,Math.min(12,Number(event.target.value))))} className="mt-1 h-8 border-0 bg-transparent p-0 text-center font-mono text-xs" aria-label={`Side ${side} ${kind} formations`}/></label>)}</div></div> }
function Mini({label,value}:{label:string;value:string|number}) { return <div className="rounded-xl border border-white/8 bg-black/25 p-2.5"><p className="text-[8px] uppercase tracking-wider text-stone-600">{label}</p><p className="mt-1 text-xs capitalize text-stone-300">{value}</p></div> }
function ResultMetric({label,value,accent=false}:{label:string;value:string;accent?:boolean}) { return <div className="rounded-xl border border-white/8 bg-black/25 p-3"><p className="text-[8px] uppercase tracking-wider text-stone-600">{label}</p><p className={`mt-1 text-lg font-semibold capitalize ${accent?"text-yellow-200":"text-stone-200"}`}>{value}</p></div> }
function Typing() { return <div className="flex gap-1.5">{[0,1,2].map(index=><span key={index} className="h-2 w-2 animate-pulse rounded-full bg-yellow-300" style={{animationDelay:`${index*140}ms`}}/>)}</div> }
function ProgressLine({label,delay=false}:{label:string;delay?:boolean}) { return <div className="flex items-center gap-2 rounded-xl border border-white/8 bg-black/25 px-3 py-2"><span className={`h-1.5 w-1.5 animate-pulse rounded-full bg-yellow-300 ${delay?"[animation-delay:180ms]":""}`}/><span className="text-[10px] text-stone-400">{label}</span></div> }
