import { useMemo, useState } from "react";
import { ChevronDown, ChevronUp, CircleDot, PackageOpen, Route, Sparkles, Target } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScenarioConfig, SimulationEvent, SimulationResult } from "@/lib/sandtable";

const eventIcons = { movement: Route, engagement: CircleDot, logistics: PackageOpen, objective: Target };

type SensitivityCase = { label: string; result: SimulationResult };
type Props = { result: SimulationResult; config: ScenarioConfig; week: number; setWeek: (week: number) => void; onSave: () => void; onShare: () => void; onSensitivity: (kind: "tempo" | "supply" | "uncertainty") => void; comparison?: SensitivityCase; saving: boolean };

export function ResultsSheet({ result, config, week, setWeek, onSave, onShare, onSensitivity, comparison, saving }: Props) {
  const [expanded, setExpanded] = useState(true);
  const [filter, setFilter] = useState<SimulationEvent["type"] | "all">("all");
  const events = useMemo(() => result.events.filter(event => event.week <= week && (filter === "all" || event.type === filter)).slice(-6).reverse(), [result, week, filter]);
  const chartData = result.frames.map(frame => ({ week: `W${frame.week}`, A: frame.aStrength, B: frame.bStrength, supplyA: frame.aSupply, supplyB: frame.bSupply }));
  return (
    <section className={`absolute inset-x-2 bottom-2 z-30 overflow-hidden rounded-[24px] border border-white/10 bg-[#0b0b0b]/96 shadow-[0_-24px_80px_rgba(0,0,0,.35)] backdrop-blur-xl transition-all duration-500 md:inset-x-4 ${expanded ? "h-[64vh] md:h-[52vh]" : "h-[82px]"}`} aria-label="Simulation results">
      <div className="flex h-[82px] items-center gap-4 border-b border-white/8 px-4 md:px-6">
        <button className="flex min-w-0 flex-1 items-center gap-3 text-left" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>
          <span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-yellow-400/12 text-yellow-300"><Sparkles className="h-4 w-4" /></span>
          <span className="min-w-0"><span className="block truncate text-sm font-semibold text-stone-100">Modeled advantage · Side {result.advantage}</span><span className="block text-xs text-stone-500">{result.confidence} confidence · {result.outcomeA}% / {result.outcomeB}% ensemble split</span></span>
        </button>
        <div className="hidden items-center gap-2 md:flex"><Button onClick={onSave} disabled={saving} variant="outline" className="rounded-xl border-white/10 bg-white/[.03] text-stone-200 hover:bg-white/[.07]">{saving ? "Saving…" : "Save study"}</Button><Button onClick={onShare} className="rounded-xl bg-yellow-400 text-[#181500] hover:bg-yellow-300">Share report</Button></div>
        <Button variant="ghost" size="icon" onClick={() => setExpanded(!expanded)} className="rounded-xl text-stone-400" aria-label={expanded ? "Collapse results" : "Expand results"}>{expanded ? <ChevronDown className="h-4 w-4" /> : <ChevronUp className="h-4 w-4" />}</Button>
      </div>
      {expanded && <div className="h-[calc(100%-82px)] overflow-y-auto px-4 py-4 md:px-6">
        <div className="mb-4 flex items-center gap-3"><span className="text-[10px] uppercase tracking-[.18em] text-stone-500">Replay</span><Slider value={[week]} max={config.duration} step={1} onValueChange={value => setWeek(value[0])} className="max-w-xl" /><span className="w-14 text-right font-mono text-xs text-yellow-200">W{String(week).padStart(2,"0")}</span></div>
        <Tabs defaultValue="overview">
          <TabsList className="h-9 rounded-xl bg-white/[.04] p-1"><TabsTrigger className="rounded-lg text-xs data-[state=active]:bg-white/10 data-[state=active]:text-white" value="overview">Overview</TabsTrigger><TabsTrigger className="rounded-lg text-xs data-[state=active]:bg-white/10 data-[state=active]:text-white" value="sensitivity">Sensitivity</TabsTrigger><TabsTrigger className="rounded-lg text-xs data-[state=active]:bg-white/10 data-[state=active]:text-white" value="events">Event log</TabsTrigger><TabsTrigger className="rounded-lg text-xs data-[state=active]:bg-white/10 data-[state=active]:text-white" value="trace">Traceability</TabsTrigger></TabsList>
          <TabsContent value="overview" className="mt-4 grid gap-4 lg:grid-cols-[1.45fr_.8fr]">
            <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="mb-2 flex items-center justify-between"><div><p className="text-sm font-medium text-stone-200">Effective strength</p><p className="text-xs text-stone-500">Canonical weekly replay</p></div><div className="flex gap-3 text-[10px] text-stone-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-yellow-400" />Side A</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-stone-300" />Side B</span></div></div><div className="h-44"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#ffffff0b" vertical={false}/><XAxis dataKey="week" stroke="#6f7776" fontSize={10} tickLine={false}/><YAxis domain={[0,100]} stroke="#6f7776" fontSize={10} tickLine={false}/><Tooltip contentStyle={{background:"#0c0c0c",border:"1px solid #ffffff18",borderRadius:12,fontSize:11}}/><Area dataKey="A" stroke="#facc15" fill="#facc15" fillOpacity={.09} strokeWidth={2}/><Line dataKey="B" stroke="#a3a3a3" dot={false} strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
            <div className="grid grid-cols-2 gap-3"><Metric label="Side A outcome" value={`${result.outcomeA}%`} note={`Loss ${result.medianLossA}% · ${result.lossRangeA[0]}–${result.lossRangeA[1]}`} accent/><Metric label="Side B outcome" value={`${result.outcomeB}%`} note={`Loss ${result.medianLossB}% · ${result.lossRangeB[0]}–${result.lossRangeB[1]}`}/><div className="col-span-2 rounded-2xl border border-yellow-400/20 bg-yellow-400/[.06] p-4"><p className="text-xs font-medium text-yellow-100">Illustrative output, not a forecast</p><p className="mt-1 text-xs leading-relaxed text-stone-400">Ranges show variation across 240 deterministic samples. They are not real-world probabilities.</p></div></div>
          </TabsContent>
          <TabsContent value="sensitivity" className="mt-4"><div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><p className="text-sm font-medium text-stone-200">Run a bounded comparison</p><p className="mt-1 text-xs leading-relaxed text-stone-500">Vary one assumption against the preserved baseline. These cases explain sensitivity; they do not optimize an outcome.</p><div className="mt-4 grid gap-2">{[["tempo","Lower tempo"],["supply","Supply stress"],["uncertainty","Higher uncertainty"]].map(([kind,label])=><Button key={kind} onClick={()=>onSensitivity(kind as "tempo"|"supply"|"uncertainty")} variant="outline" className="justify-start rounded-xl border-white/10 bg-transparent text-xs text-stone-300 hover:bg-white/5">{label}</Button>)}</div></div><div className="rounded-2xl border border-white/8 bg-white/[.025] p-4">{comparison?<><p className="text-[10px] uppercase tracking-[.16em] text-yellow-300">{comparison.label}</p><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Baseline side A" value={`${result.outcomeA}%`} note={`${result.confidence} confidence`}/><Metric label="Comparison side A" value={`${comparison.result.outcomeA}%`} note={`${comparison.result.outcomeA-result.outcomeA>=0?"+":""}${comparison.result.outcomeA-result.outcomeA} point change`} accent/></div><p className="mt-4 text-xs leading-relaxed text-stone-500">Comparison uses the same unified force layer with a derived deterministic seed.</p></>:<div className="grid h-full min-h-40 place-items-center text-center text-xs text-stone-600">Choose one case to compare with the active baseline.</div>}</div></div></TabsContent>
          <TabsContent value="events" className="mt-4"><div className="mb-3 flex flex-wrap gap-2">{(["all","movement","engagement","logistics","objective"] as const).map(type => <button key={type} onClick={() => setFilter(type)} className={`rounded-full border px-3 py-1.5 text-[10px] uppercase tracking-wider ${filter===type?"border-yellow-400/40 bg-yellow-400/10 text-yellow-200":"border-white/10 text-stone-500"}`}>{type}</button>)}</div><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{events.map(event => { const Icon=eventIcons[event.type]; return <div key={event.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-3"><div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5 text-yellow-300"/><span className="text-[10px] uppercase tracking-wider text-stone-500">Week {event.week} · {event.type}</span></div><p className="mt-2 text-sm text-stone-200">{event.title}</p><p className="mt-1 text-xs leading-relaxed text-stone-500">{event.detail}</p></div>})}</div></TabsContent>
          <TabsContent value="trace" className="mt-4 grid gap-3 md:grid-cols-2"><Trace label="Model version" value={result.modelVersion}/><Trace label="Dataset version" value={result.datasetVersion}/><Trace label="Named seed" value={result.seed}/><Trace label="Run key" value={result.runKey}/><div className="md:col-span-2 rounded-2xl border border-white/8 p-4"><p className="text-xs font-medium text-stone-200">Assumptions & limitations</p><ul className="mt-2 grid gap-2 text-xs leading-relaxed text-stone-500 md:grid-cols-2">{[...result.assumptions,...result.limitations].map(item=><li key={item} className="flex gap-2"><span className="text-yellow-300">•</span>{item}</li>)}</ul></div></TabsContent>
        </Tabs>
      </div>}
    </section>
  );
}
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}) { return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-[.14em] text-stone-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${accent?"text-yellow-200":"text-stone-100"}`}>{value}</p><p className="mt-1 text-[11px] text-stone-500">{note}</p></div> }
function Trace({label,value}:{label:string;value:string}) { return <div className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><p className="text-[10px] uppercase tracking-[.14em] text-stone-500">{label}</p><p className="mt-2 break-all font-mono text-xs text-stone-200">{value}</p></div> }
