import { ChangeEvent } from "react";
import { Play, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Textarea } from "@/components/ui/textarea";
import { Nation, ScenarioConfig } from "@/lib/sandtable";

type Props = { open: boolean; onClose: () => void; config: ScenarioConfig; setConfig: (config: ScenarioConfig) => void; nations: Nation[]; onRun: () => void; onAi: (prompt: string) => void; running: boolean };

export function ScenarioPanel({ open, onClose, config, setConfig, nations, onRun, onAi, running }: Props) {
  const patch = <K extends keyof ScenarioConfig>(key: K, value: ScenarioConfig[K]) => setConfig({ ...config, [key]: value });
  const patchSide = (side: "sideA" | "sideB", key: string, value: unknown) => setConfig({ ...config, [side]: { ...config[side], [key]: value } });
  const promptScenario = (event: ChangeEvent<HTMLTextAreaElement>) => event.currentTarget.dataset.value = event.target.value;
  return <aside className={`absolute bottom-24 left-2 top-20 z-40 w-[calc(100%-1rem)] max-w-[380px] rounded-[24px] border border-white/10 bg-[#0b0b0b]/97 shadow-2xl backdrop-blur-xl transition-transform duration-300 md:bottom-4 md:left-4 ${open ? "translate-x-0" : "-translate-x-[110%]"}`} aria-hidden={!open}>
    <div className="flex h-16 items-center justify-between border-b border-white/8 px-5"><div><p className="text-sm font-semibold text-stone-100">Scenario setup</p><p className="text-[11px] text-stone-500">Review inputs before resolution</p></div><Button variant="ghost" size="icon" onClick={onClose} className="rounded-xl text-stone-500" aria-label="Close scenario panel"><X className="h-4 w-4"/></Button></div>
    <div className="h-[calc(100%-136px)] space-y-5 overflow-y-auto p-5">
      <section><div className="mb-3 flex items-center gap-2 text-[10px] uppercase tracking-[.18em] text-stone-500"><Sparkles className="h-3 w-3 text-yellow-300"/>AI-assisted draft</div><Textarea id="aiPrompt" data-value="" onChange={promptScenario} placeholder="Describe an abstract, non-operational study…" className="min-h-20 rounded-2xl border-white/10 bg-white/[.03] text-sm text-stone-200 placeholder:text-stone-600"/><Button onClick={() => { const el=document.getElementById("aiPrompt") as HTMLTextAreaElement; onAi(el?.value || "Balanced access-zone scenario under mixed terrain"); }} variant="outline" className="mt-2 h-9 rounded-xl border-white/10 bg-transparent text-xs text-stone-300 hover:bg-white/5">Draft reviewable proposal</Button></section>
      <section className="space-y-3"><div className="text-[10px] uppercase tracking-[.18em] text-stone-500">Study identity</div><Field label="Scenario name"><Input value={config.name} onChange={e=>patch("name",e.target.value)} className="control"/></Field><Field label="Region label"><Input value={config.regionLabel} onChange={e=>patch("regionLabel",e.target.value)} className="control"/></Field><Field label="Abstract objective"><Input value={config.objective} onChange={e=>patch("objective",e.target.value)} className="control"/></Field></section>
      <section className="grid grid-cols-2 gap-3"><NationField label="Side A" value={config.sideA.nationCode} nations={nations.filter(n=>n.code!==config.sideB.nationCode)} onChange={v=>patchSide("sideA","nationCode",v)}/><NationField label="Side B" value={config.sideB.nationCode} nations={nations.filter(n=>n.code!==config.sideA.nationCode)} onChange={v=>patchSide("sideB","nationCode",v)}/></section>
      <section className="grid grid-cols-2 gap-3"><SelectField label="Terrain" value={config.terrain} values={["open","mixed","restricted","maritime"]} onChange={v=>patch("terrain",v as ScenarioConfig["terrain"])}/><SelectField label="Tempo" value={config.tempo} values={["measured","standard","intense"]} onChange={v=>patch("tempo",v as ScenarioConfig["tempo"])}/><SelectField label="A posture" value={config.sideA.posture} values={["defensive","balanced","assertive"]} onChange={v=>patchSide("sideA","posture",v)}/><SelectField label="B posture" value={config.sideB.posture} values={["defensive","balanced","assertive"]} onChange={v=>patchSide("sideB","posture",v)}/></section>
      <section className="space-y-4"><div className="text-[10px] uppercase tracking-[.18em] text-stone-500">Time & uncertainty</div><RangeField label="Duration" value={config.duration} min={4} max={24} suffix=" weeks" onChange={v=>patch("duration",v)}/><RangeField label="Uncertainty" value={config.uncertainty} min={10} max={90} suffix="%" onChange={v=>patch("uncertainty",v)}/></section>
      {(["sideA","sideB"] as const).map((side,index)=><section key={side} className="space-y-4 rounded-2xl border border-white/8 bg-white/[.02] p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[.18em] text-stone-500">Side {index===0?"A":"B"} posture</span><span className={`h-2 w-2 rounded-full ${index===0?"bg-yellow-400":"bg-stone-300"}`}/></div><RangeField label="Allocation" value={config[side].allocation} min={20} max={100} suffix="%" onChange={v=>patchSide(side,"allocation",v)}/><RangeField label="Initial supply" value={config[side].supply} min={20} max={100} suffix="%" onChange={v=>patchSide(side,"supply",v)}/><RangeField label="Support capacity" value={config[side].support} min={10} max={100} suffix="%" onChange={v=>patchSide(side,"support",v)}/><RangeField label="Reinforcement" value={config[side].reinforcements} min={0} max={60} suffix="%" onChange={v=>patchSide(side,"reinforcements",v)}/><FormationGrid sideLabel={`Side ${index===0?"A":"B"}`} formations={config[side].formations} onChange={(kind,value)=>patchSide(side,"formations",{...config[side].formations,[kind]:value})}/></section>)}
      <Field label="Deterministic seed"><Input value={config.seed} onChange={e=>patch("seed",e.target.value.toUpperCase())} className="control font-mono"/></Field>
      <div className="rounded-2xl border border-yellow-400/15 bg-yellow-400/[.05] p-3 text-[11px] leading-relaxed text-stone-500">Aggregate educational modeling only. Real locations, targeting, routes, evasion, and operational recommendations are prohibited.</div>
    </div>
    <div className="flex h-[72px] items-center gap-2 border-t border-white/8 px-5"><Button onClick={onRun} disabled={running || config.sideA.nationCode===config.sideB.nationCode} className="h-11 flex-1 rounded-2xl bg-yellow-400 font-semibold text-[#181500] hover:bg-yellow-300"><Play className="mr-2 h-4 w-4 fill-current"/>{running?"Resolving 240 samples…":"Run simulation"}</Button><Button variant="outline" size="icon" className="h-11 w-11 rounded-2xl border-white/10 bg-white/[.03] text-stone-400" aria-label="Advanced scenario settings"><SlidersHorizontal className="h-4 w-4"/></Button></div>
  </aside>;
}
function Field({label,children}:{label:string;children:React.ReactNode}) { return <div><Label className="mb-1.5 block text-[11px] text-stone-500">{label}</Label>{children}</div> }
function NationField({label,value,nations,onChange}:{label:string;value:string;nations:Nation[];onChange:(v:string)=>void}) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger className="control"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111111] text-stone-200">{nations.map(n=><SelectItem key={n.code} value={n.code}>{n.code} · {n.name}</SelectItem>)}</SelectContent></Select></Field> }
function SelectField({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger className="control capitalize"><SelectValue/></SelectTrigger><SelectContent className="border-white/10 bg-[#111111] text-stone-200">{values.map(v=><SelectItem className="capitalize" key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field> }
function RangeField({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(v:number)=>void}) { return <div><div className="mb-2 flex justify-between text-[11px]"><span className="text-stone-500">{label}</span><span className="font-mono text-stone-300">{value}{suffix}</span></div><Slider value={[value]} min={min} max={max} onValueChange={v=>onChange(v[0])}/></div> }
function FormationGrid({sideLabel,formations,onChange}:{sideLabel:string;formations:ScenarioConfig["sideA"]["formations"];onChange:(kind:keyof ScenarioConfig["sideA"]["formations"],value:number)=>void}) { return <div><p className="mb-2 text-[11px] text-stone-500">Aggregate formations · {sideLabel}</p><div className="grid grid-cols-4 gap-2">{(["land","air","naval","support"] as const).map(kind=><label key={kind} className="rounded-xl border border-white/8 bg-black/30 p-2 text-center"><span className="block text-[9px] capitalize text-stone-500">{kind}</span><Input type="number" min={0} max={12} value={formations[kind]} onChange={event=>onChange(kind,Math.max(0,Math.min(12,Number(event.target.value))))} className="mt-1 h-7 border-0 bg-transparent p-0 text-center font-mono text-xs text-stone-200 focus-visible:ring-1" aria-label={`${sideLabel} ${kind} formations`}/></label>)}</div></div> }
