import { GitCompareArrows, History, RotateCcw, Share2, Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScenarioConfig, SimulationResult } from "@/lib/sandtable";

export type HistoricalRun = { id: string; run_key: string; seed: string; model_version: string; dataset_version: string; configuration: ScenarioConfig; result: SimulationResult; created_at: string };
export type SavedStudy = { id: string; name: string; region_label: string; configuration: ScenarioConfig; latest_result: SimulationResult | null; share_token: string; updated_at: string; simulation_runs?: HistoricalRun[] };

type Props = { open: boolean; onOpenChange: (open:boolean)=>void; studies: SavedStudy[]; hasActiveResult: boolean; onOpenStudy: (study:SavedStudy)=>void; onOpenRun:(study:SavedStudy,run:HistoricalRun)=>void; onCompareRun:(run:HistoricalRun)=>void; onDelete:(study:SavedStudy)=>void };

export function StudyLibrary({ open, onOpenChange, studies, hasActiveResult, onOpenStudy, onOpenRun, onCompareRun, onDelete }: Props) {
  const navigate = useNavigate();
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-1rem)] w-[calc(100vw-1rem)] max-w-3xl overflow-hidden rounded-[24px] p-4 sm:rounded-[28px] sm:p-6 border-white/10 bg-[#0c0c0c] text-stone-100"><DialogHeader><DialogTitle>Shared study library</DialogTitle><DialogDescription className="text-stone-500">Completed studies can change; each stored run below remains immutable.</DialogDescription></DialogHeader><div className="max-h-[calc(100dvh-9rem)] space-y-3 overflow-y-auto pr-1">{studies.length===0?<div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-stone-500">No studies saved yet.</div>:studies.map(study=><section key={study.id} className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><div className="flex items-center gap-3"><button onClick={()=>onOpenStudy(study)} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium text-stone-200">{study.name}</p><p className="mt-1 text-[11px] text-stone-500">{study.region_label} · updated {new Date(study.updated_at).toLocaleDateString()}</p></button><Button onClick={()=>navigate(`/share/${study.share_token}`)} variant="ghost" size="icon" className="rounded-xl text-stone-500" aria-label="Open shared report"><Share2 className="h-4 w-4"/></Button><Button onClick={()=>onDelete(study)} variant="ghost" size="icon" className="rounded-xl text-stone-600 hover:text-red-300" aria-label="Delete study"><Trash2 className="h-4 w-4"/></Button></div><div className="mt-3 border-t border-white/8 pt-3"><div className="mb-2 flex items-center gap-2 text-[9px] uppercase tracking-[.16em] text-stone-600"><History className="h-3 w-3"/>Immutable run history · {study.simulation_runs?.length ?? 0}</div><div className="space-y-1.5">{study.simulation_runs?.map(run=><div key={run.id} className="flex items-center gap-1 rounded-xl sm:gap-2 border border-white/6 bg-black/30 px-3 py-2"><button onClick={()=>onOpenRun(study,run)} className="min-w-0 flex-1 text-left"><p className="truncate font-mono text-[10px] text-stone-300">{run.run_key}</p><p className="mt-0.5 text-[9px] text-stone-600">{new Date(run.created_at).toLocaleString()} · seed {run.seed}</p></button><Button onClick={()=>onOpenRun(study,run)} variant="ghost" size="icon" className="h-10 w-10 rounded-lg text-stone-500 sm:h-8 sm:w-8" aria-label="Reopen historical run"><RotateCcw className="h-3.5 w-3.5"/></Button>{hasActiveResult&&<Button onClick={()=>onCompareRun(run)} variant="ghost" size="icon" className="h-10 w-10 rounded-lg text-yellow-300 sm:h-8 sm:w-8" aria-label="Compare historical run"><GitCompareArrows className="h-3.5 w-3.5"/></Button>}</div>)}</div></div></section>)}</div></DialogContent></Dialog>;
}
