// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://dusknfxdackvdmcmyavq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_LvC-8m6mTf7Q5J5RW4lLlQ_Z7j3JUBF";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
